### ISSUE TITLE
ccgms2021

### ISSUE THREAD

**Issue by Sutehktd** [dabonetn/Link232-Wifi#1]
Hello,

I can connect to the link 232 Wifi cartridge modem through ccgms terminal software. Also connected to my wifi network. I can change settings through at commands and see modem status with ATI....however I can't connect to any bbs. I am using the Swiftlink/turbo DE setting at 19200 baud but when I try and connect I get "error" changing to lower baud rates in terminal and in modem with at commands gets me garbage characters on the screen. It does say dialing and connecting when I try.

Any ideas what I am doing wrong?

Thanks.
-Sutehk

**Comment by dabonetn** [comment]
Sorry, I just noticed the open issues. Did you get this resolved?
