### ISSUE TITLE
"Link232-Wifi-cartridge-bottom.stl" does not match top half of the case.

### ISSUE THREAD

**Issue by hackup** [dabonetn/Link232-Wifi#2]
Thanks for sharing this nice project! 

I just noticed a minor issue: The "Link232-Wifi-cartridge-bottom.stl" model does not seem to match the top half of the case. It seems to short and the center hole is in the wrong position. The "Number4screw" variant on the other hand looks fine. I would suggest to either fix the model or to remove it from the repo.

**Comment by dabonetn** [comment]
Thanks, I'm just now noticing the open issues, I never got a email. 
Deleting the wrong model now.
